export const APP_NAME = "AI Interview Pro";

export const SUBJECTS = [
  {
    id: "java",
    name: "Java",
    icon: "☕",
    color: "#f59e0b",
    description: "Core Java, OOP, Collections, Multithreading",
    topics: ["OOP", "Collections", "Multithreading", "Spring Boot"],
  },
  {
    id: "python",
    name: "Python",
    icon: "🐍",
    color: "#10b981",
    description: "Python fundamentals, Libraries, Frameworks",
    topics: ["Basics", "Django", "Flask", "NumPy"],
  },
  {
    id: "javascript",
    name: "JavaScript",
    icon: "⚡",
    color: "#f59e0b",
    description: "ES6+, Async, DOM, Node.js",
    topics: ["ES6+", "Async/Await", "DOM", "Node.js"],
  },
  {
    id: "react",
    name: "React",
    icon: "⚛️",
    color: "#06b6d4",
    description: "Hooks, State, Context, Performance",
    topics: ["Hooks", "Context", "Redux", "Next.js"],
  },
  {
    id: "dbms",
    name: "DBMS",
    icon: "🗄️",
    color: "#8b5cf6",
    description: "SQL, Normalization, Transactions, Indexing",
    topics: ["SQL", "Normalization", "Indexing", "Transactions"],
  },
  {
    id: "os",
    name: "Operating Systems",
    icon: "💻",
    color: "#3b82f6",
    description: "Processes, Memory, Scheduling, Deadlocks",
    topics: ["Processes", "Memory", "Scheduling", "Deadlocks"],
  },
  {
    id: "dsa",
    name: "Data Structures",
    icon: "🌳",
    color: "#ec4899",
    description: "Arrays, Trees, Graphs, Dynamic Programming",
    topics: ["Arrays", "Trees", "Graphs", "DP"],
  },
  {
    id: "ml",
    name: "Machine Learning",
    icon: "🤖",
    color: "#10b981",
    description: "Supervised, Unsupervised, Neural Networks",
    topics: ["Regression", "Classification", "Neural Nets", "NLP"],
  },
  {
    id: "ai",
    name: "Artificial Intelligence",
    icon: "🧠",
    color: "#8b5cf6",
    description: "Search, Logic, Planning, Knowledge Representation",
    topics: ["Search", "Logic", "Planning", "Agents"],
  },
];

export const DIFFICULTIES = [
  {
    id: "easy",
    name: "Easy",
    color: "#10b981",
    description: "Beginner friendly questions",
    questions: 10,
  },
  {
    id: "medium",
    name: "Medium",
    color: "#f59e0b",
    description: "Intermediate level questions",
    questions: 10,
  },
  {
    id: "hard",
    name: "Hard",
    color: "#ef4444",
    description: "Advanced level questions",
    questions: 10,
  },
];

export const NAV_LINKS = [
  { label: "Features", href: "#features" },
  { label: "Subjects", href: "#subjects" },
  { label: "Testimonials", href: "#testimonials" },
  { label: "Pricing", href: "#pricing" },
];

export const STATS = [
  { value: "50K+", label: "Interviews Conducted" },
  { value: "92%", label: "Success Rate" },
  { value: "200+", label: "Questions Per Subject" },
  { value: "4.9★", label: "Average Rating" },
];

export const FEATURES = [
  {
    icon: "🧠",
    title: "AI-Powered Questions",
    description:
      "Dynamic questions generated by Claude AI tailored to your skill level and subject.",
    color: "#8b5cf6",
  },
  {
    icon: "🎙️",
    title: "Voice Recognition",
    description:
      "Answer questions naturally using your voice. Whisper AI transcribes with high accuracy.",
    color: "#3b82f6",
  },
  {
    icon: "📊",
    title: "Instant Feedback",
    description:
      "Get detailed feedback on every answer with scores, improvements and suggestions.",
    color: "#06b6d4",
  },
  {
    icon: "📈",
    title: "Progress Tracking",
    description:
      "Track your performance over time with detailed analytics and insights.",
    color: "#10b981",
  },
  {
    icon: "🎯",
    title: "Adaptive Difficulty",
    description:
      "System adapts to your performance and increases difficulty as you improve.",
    color: "#ec4899",
  },
  {
    icon: "🏆",
    title: "Achievements",
    description:
      "Earn badges and achievements as you practice and improve your skills.",
    color: "#f59e0b",
  },
];

export const TESTIMONIALS = [
  {
    name: "Arjun Sharma",
    role: "Software Engineer at Google",
    avatar: "AS",
    content:
      "AI Interview Pro helped me crack my Google interview. The AI feedback was incredibly detailed and helped me identify my weak areas.",
    rating: 5,
    color: "#8b5cf6",
  },
  {
    name: "Priya Patel",
    role: "Frontend Developer at Meta",
    avatar: "PP",
    content:
      "The React and JavaScript interview prep was spot on. Questions were very similar to what I faced in real interviews.",
    rating: 5,
    color: "#3b82f6",
  },
  {
    name: "Rahul Verma",
    role: "Data Scientist at Amazon",
    avatar: "RV",
    content:
      "The ML and AI sections are outstanding. Practiced for 2 weeks and landed my dream job at Amazon.",
    rating: 5,
    color: "#06b6d4",
  },
  {
    name: "Sneha Reddy",
    role: "Backend Engineer at Microsoft",
    avatar: "SR",
    content:
      "DBMS and OS questions were exactly what I needed. The voice feature made practice feel like a real interview.",
    rating: 5,
    color: "#10b981",
  },
];

export const FIREBASE_COLLECTIONS = {
  USERS: "users",
  SESSIONS: "sessions",
  QUESTIONS: "questions",
  FEEDBACK: "feedback",
};

export const INTERVIEW_STATUS = {
  IDLE: "idle",
  STARTING: "starting",
  ACTIVE: "active",
  PAUSED: "paused",
  COMPLETED: "completed",
  ERROR: "error",
};

export const MAX_QUESTIONS = 10;
export const QUESTION_TIME_LIMIT = 120;
export const MIN_ANSWER_LENGTH = 20;